#!/usr/bin/env python3
"""generate_brush_masks.py

Scan PNG brushes and generate a JS file with alpha masks for each brush,
so the web animator can use them without loading external images at paint time.

Usage (from the project root, where index.html lives):

    python generate_brush_masks.py \
        --definitions brushes_definitions.js \
        --brush-root . \
        --output brush_masks.js \
        --size 64

Requires Pillow:

    pip install pillow

"""

import argparse
import json
import os
import re
from PIL import Image


def parse_brush_definitions(path):
    """Parse brushes_definitions.js and return list of (id, file) tuples."""
    with open(path, "r", encoding="utf-8") as f:
        src = f.read()

    # Very lightweight regex-based parser:
    # matches objects like { id: 'brush_01', ..., file: 'brushes/brush_01.png', ... }
    pattern = re.compile(
        r"\{[^}]*?id:\s*'([^']+)'[^}]*?file:\s*'([^']+)'[^}]*?\}",
        re.DOTALL,
    )
    matches = pattern.findall(src)

    if not matches:
        raise RuntimeError("No brush definitions with id/file found in %s" % path)

    return matches


def build_mask_for_image(img_path, mask_size):
    """Open image, resample to (mask_size x mask_size), return flat alpha array 0..255."""
    if not os.path.isfile(img_path):
        raise FileNotFoundError(img_path)

    img = Image.open(img_path).convert("RGBA")
    if mask_size is not None:
        img = img.resize((mask_size, mask_size), Image.LANCZOS)

    w, h = img.size
    alpha = img.split()[-1]  # alpha channel
    data = list(alpha.getdata())  # list of length w*h with 0..255

    return w, h, data


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--definitions",
        default="brushes_definitions.js",
        help="Path to brushes_definitions.js",
    )
    ap.add_argument(
        "--brush-root",
        default=".",
        help="Project root / base directory for brush file paths (default: current dir)",
    )
    ap.add_argument(
        "--output",
        default="brush_masks.js",
        help="Output JS file to write (default: brush_masks.js)",
    )
    ap.add_argument(
        "--size",
        type=int,
        default=64,
        help="Mask resolution (width=height=SIZE). Use None or 0 to keep original size.",
    )

    args = ap.parse_args()

    defs_path = args.definitions
    root = args.brush_root
    out_path = args.output
    mask_size = args.size if args.size and args.size > 0 else None

    brushes = parse_brush_definitions(defs_path)

    masks = {}
    for brush_id, file_rel in brushes:
        img_path = os.path.join(root, file_rel)
        print(f"Processing {brush_id}: {img_path}")
        w, h, data = build_mask_for_image(img_path, mask_size)
        masks[brush_id] = {
            "width": w,
            "height": h,
            "data": data,
        }

    # Write JS file
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by generate_brush_masks.py - DO NOT EDIT BY HAND\n")
        f.write("// Contains pre-baked alpha masks for texture brushes.\n\n")
        f.write("var BRUSH_MASKS = ")  # global var
        json.dump(masks, f, separators=(",", ":"))  # compact JSON
        f.write(";\n")

    print("Wrote", out_path)


if __name__ == "__main__":
    main()
